name: mahati_mobile
version: 1.4.5
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  sizer: ^2.0.15
  http: ^1.2.1
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.8
  flutter_floating_bottom_bar: ^1.2.0
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  pinch_zoom: ^2.0.0
  syncfusion_flutter_charts: ^25.2.3+1
  easy_date_timeline: ^1.0.7
  flutter_local_notifications: ^17.1.2
  intl: ^0.19.0
  timezone: ^0.9.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  open_file: ^3.3.2
  assets_audio_player: ^3.1.1
  google_generative_ai: ^0.4.3
  cached_network_image: ^3.3.1
  flutter_cached_pdfview: ^0.4.2
  flutter_slidable: ^3.1.1
  http_parser: ^4.0.2
  onesignal_flutter: ^5.2.2
  firebase_core: ^3.3.0
  flutter_reactive_ble: ^5.3.1
  accordion: ^2.6.0
  whatsapp_unilink: ^2.1.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_dotenv: ^5.2.1
  pinput: ^5.0.1
  email_otp: ^3.0.2
  intl_phone_field: ^3.2.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/animations/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
