name: mahati_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  sizer: ^2.0.15
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.8
  flutter_floating_bottom_bar: ^1.2.0
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  image_picker: ^1.1.1
  google_ml_kit: ^0.18.0
  carousel_slider: ^4.2.1
  flutter_tesseract_ocr: ^0.3.7
  pinch_zoom: ^2.0.0
  syncfusion_flutter_charts: ^25.1.42
  easy_date_timeline: ^1.0.6

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/animations/
    - assets/tessdata/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
